flowchart TD

    Root ---> solarSystem
    solarSystem ---> sunMesh
    solarSystem ---> earthTrack
    earthTrack ---> earthOrbit
    earthOrbit ---> earthMesh
    earthOrbit ---> moonTrack
    moonTrack ---> moonMesh

